/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import dev.*;
import java.util.ArrayList;

/**
 *
 * @author Luke
 */
public class InterfaceRelatorio extends javax.swing.JPanel {
    int totalVotos;
    int votosBranco;
    int votosNulo;
    Partido[] partidos;
    ArrayList<Candidato> candidatos;
    Candidato candidato = new Candidato();
    
public InterfaceRelatorio(int totalVotos, int votosBranco, int votosNulo, Partido[] partidos) {
        this.totalVotos = totalVotos;
        this.votosBranco = votosBranco;
        this.votosNulo = votosNulo;
        this.partidos = partidos;
        initComponents();
        criarRelatorio();

    }

    public void criarRelatorio() {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 4; i++) {
            sb.append("Partido " + partidos[i].getNome() + ":\n");
            candidatos = partidos[i].getCandidatos();
            for (int j = 0; j < candidatos.size(); j++) {
                candidato = candidatos.get(j);
                sb.append("Candidato " + candidato.getNome() + ": " + candidato.getNumVotos() + " votos.\n");
            }
            sb.append("\n");
        }
        sb.append("\n Nulos: "+votosNulo+"\n Brancos: "+votosBranco+"\n TOTAL VOTOS: "+totalVotos);
        txtRelatorio.setText(sb.toString());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRelatorio = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Relatório de Votação");

        txtRelatorio.setColumns(20);
        txtRelatorio.setRows(5);
        jScrollPane1.setViewportView(txtRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtRelatorio;
    // End of variables declaration//GEN-END:variables
}
